# Generated by Django 3.0 on 2020-04-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=50, null=True)),
                ('imageUrl', models.CharField(max_length=400, null=True)),
                ('audioUrl', models.CharField(max_length=400, null=True)),
                ('language', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
