# Generated by Django 3.0 on 2020-04-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='searchQuery',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
