# Generated by Django 3.0 on 2020-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsearch', '0002_user_searchquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='choice',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='user',
            name='audioUrl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='user',
            name='requireLanguage',
            field=models.BooleanField(default=0),
        ),
    ]
