# Generated by Django 3.0 on 2020-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsearch', '0003_auto_20200422_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changeLanguageOrService',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='requireService',
            field=models.BooleanField(default=True),
        ),
    ]
