# Generated by Django 3.0 on 2020-04-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsearch', '0004_auto_20200423_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requireUseOldData',
            field=models.BooleanField(default=False),
        ),
    ]
